//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDb
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Department { get; set; }
        public Nullable<int> Salary { get; set; }
    }
}
